- name: Deploy application
  hosts: windows
  gather_facts: yes
  vars:
    git_repo_url: "https://github.com/Npraveenreddy/training.git"
    folders:
      AuthorizationPortal: 0
      AuthorizationPortalAPI: 0
      AutoAuthAPI: 0
      CloudAPI: 1
      FicoAPI: 0
      InterqualConnect: 0
      MCG: 0
      MemberServices: 0
      MemberServicesAPI: 0
      Portal: 1
      ProviderRegistration: 0
      RealTimeADT: 0
      RealTimeADTAPI: 0
      RealTimeAPI: 0
      ServiceProvider: 0
      SSISAPI: 0
      SmartComm: 1
  tasks:
    - name: Clone the Git repository
      ansible.windows.win_shell: |
         git clone {{ git_repo_url }} C:\inetpub\wwwroot\deployment\temp_repo
      args:
        creates: C:\inetpub\wwwroot\deployment\temp_repo
      when: folders.Portal == 1 or folders.SmartComm == 1 or folders.ClouAPI == 1

    - name: Ensure destination folders exist
      ansible.windows.win_file:
        state: directory
        path: "C:\\inetpub\\wwwroot\\deployment\\{{ item.key }}"
      loop: "{{ folders | dict2items }}"
      when: item.value == 1

    - name: Copy the folders from the cloned repository
      ansible.windows.win_shell: |
        if (Test-Path -Path C:\inetpub\wwwroot\deployment\temp_repo\{{ item.key }}) {
          Copy-Item -Path C:\inetpub\wwwroot\deployment\temp_repo\{{ item.key }}\* -Destination C:\inetpub\wwwroot\deployment\{{ item.key }} -Recurse -Force
        } else {
          Write-Host "Source path C:\inetpub\wwwroot\deployment\temp_repo\{{ item.key }} does not exist."
        }
      loop: "{{ folders | dict2items }}"
      when: item.value == 1
    - name: Remove the temporary repository folder
      ansible.windows.win_file:
        path: C:\inetpub\wwwroot\deployment\temp_repo
        state: absent
      when: folders.Portal == 1 or folders.SmartComm == 1 or folders.ClouAPI == 1