name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          apt install software-properties-common
          add-apt-repository --yes --update ppa:ansible/ansible
          apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook -i hosts.ini infra.yml -vvv
