name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i hosts.ini infra.yml -vvv
