name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ansible

    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Playbook
        run: |
          ls
         # ansible-playbook -i hosts.ini infra.yml -vvv
